spring.application.name=SpringBootWebFlux_Assign2_Ariunjargal

logging.level.org.springframework=ERROR
logging.level.com=TRACE
server.port=8084

spring.mongodb.host=localhost
spring.mongodb.port=27017
spring.mongodb.database=humber